### ISSUE TITLE
发现有相同考号相同成绩，但是多条记录的bug

### ISSUE THREAD

**Issue by kouhkh** [csflyer/USTCrank#5]
第一页有
![F@098EW77PCAE3$8~{2_JBA](https://user-images.githubusercontent.com/47654808/155911572-7d8cf8f7-744d-4ab3-9c6f-df0d978a3ef4.png)
第二页有
![N( HTNWPSM8{3{_6MLMJ{ZM](https://user-images.githubusercontent.com/47654808/155911579-fdec6ad2-16ca-4a58-b9c2-fc748c0a150c.png)
还有几对重复记录，用excel发现的。。。
[成绩表.xls](https://github.com/csflyer/USTCrank/files/8149976/default.xls)
python不太懂，可能检查一下考号重复的记录，删掉就行了

**Comment by csflyer** [comment]
确实存在，考号是主键，不存在重复的情况，应该是输出排名的时候，只按分数排，不是稳定的，加上跨页了，所以一条记录可能出现在两个页面中，我改一下

**Comment by csflyer** [comment]
已经让其他同学把修改部署到线上了，可以再试一下，感谢同学发现并提出问题
